-- ATENCIÓN:
-- Si quieres limpiar todo y empezar de cero, ejecuta primero:
-- drop table if exists public.athlete_results cascade;
-- drop table if exists public.sync_status cascade;

create table if not exists public.athlete_results (
  id bigint generated by default as identity primary key,
  source_file_id text,
  source_file_name text,
  source_modified_time timestamptz,
  sheet_name text,
  row_number integer,

  -- Mapeo real del Excel:
  -- "Denominación Prueba" -> event_name
  -- "Marca" -> mark_raw
  -- "Atleta" -> athlete_name
  -- "Categoría atleta" -> category
  -- "Licencia: Nombre comercial" -> club_name
  event_name text,
  event_group text,
  surface text,
  event_gender text,
  mark_raw text,
  mark_value double precision,
  athlete_name text,
  category text,
  club_name text,

  -- Campos informativos si existen en el Excel
  result_date text,
  result_place text,
  position_raw text,

  imported_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Compatibilidad si la tabla ya existía antes de esta versión
alter table public.athlete_results add column if not exists event_group text;
alter table public.athlete_results add column if not exists surface text;
alter table public.athlete_results add column if not exists event_gender text;

-- Relleno inicial para datos ya importados anteriormente
update public.athlete_results
set
  event_group = trim(regexp_replace(coalesce(event_name, ''), '(\s|\.)+(AL|PC)$', '', 'i')),
  surface = upper(substring(coalesce(event_name, '') from '(?:\s|\.)(AL|PC)$')),
  event_gender = case
    when lower(coalesce(event_name, '')) like '%fem%' then 'F'
    when lower(coalesce(event_name, '')) like '%masc%' then 'M'
    else null
  end
where event_group is null or event_group = '';

create index if not exists idx_athlete_results_category on public.athlete_results(category);
create index if not exists idx_athlete_results_event on public.athlete_results(event_name);
create index if not exists idx_athlete_results_event_group on public.athlete_results(event_group);
create index if not exists idx_athlete_results_event_gender on public.athlete_results(event_gender);
create index if not exists idx_athlete_results_club on public.athlete_results(club_name);
create index if not exists idx_athlete_results_athlete on public.athlete_results(athlete_name);
create index if not exists idx_athlete_results_mark on public.athlete_results(mark_value);
create index if not exists idx_athlete_results_source on public.athlete_results(source_file_id);
create index if not exists idx_athlete_results_filters on public.athlete_results(category, event_group, club_name, athlete_name);

create table if not exists public.sync_status (
  id integer primary key default 1,
  source_file_id text,
  source_file_name text,
  source_modified_time timestamptz,
  last_success_at timestamptz,
  last_error text,
  last_error_at timestamptz,
  imported_rows integer default 0,
  updated_at timestamptz default now()
);

insert into public.sync_status (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.ranking_results (
  id bigint generated by default as identity primary key,
  category text,
  event_group text,
  event_name text,
  event_gender text,
  surface text,
  athlete_name text,
  club_name text,
  mark_raw text,
  mark_value double precision,
  source_file_id text,
  source_file_name text,
  source_modified_time timestamptz,
  result_date text,
  result_place text,
  rank integer,
  updated_at timestamptz default now()
);

create index if not exists idx_ranking_results_category on public.ranking_results(category);
create index if not exists idx_ranking_results_event_group on public.ranking_results(event_group);
create index if not exists idx_ranking_results_club on public.ranking_results(club_name);
create index if not exists idx_ranking_results_athlete on public.ranking_results(athlete_name);
create index if not exists idx_ranking_results_rank on public.ranking_results(category, event_group, rank);
create index if not exists idx_ranking_results_filters on public.ranking_results(category, event_group, club_name, athlete_name, rank);
