create table if not exists public.athlete_results (
  id bigint generated by default as identity primary key,
  source_file_id text,
  source_file_name text,
  source_modified_time timestamptz,
  sheet_name text,
  row_number integer,
  category text,
  athlete_name text,
  club_name text,
  event_name text,
  mark_raw text,
  mark_value double precision,
  position_raw text,
  imported_at timestamptz default now()
);

create index if not exists idx_athlete_results_category on public.athlete_results(category);
create index if not exists idx_athlete_results_event on public.athlete_results(event_name);
create index if not exists idx_athlete_results_club on public.athlete_results(club_name);
create index if not exists idx_athlete_results_athlete on public.athlete_results(athlete_name);
create index if not exists idx_athlete_results_mark on public.athlete_results(mark_value);
create index if not exists idx_athlete_results_source on public.athlete_results(source_file_id);

create table if not exists public.sync_status (
  id integer primary key default 1,
  source_file_id text,
  source_file_name text,
  source_modified_time timestamptz,
  last_success_at timestamptz,
  last_error text,
  last_error_at timestamptz,
  imported_rows integer default 0,
  updated_at timestamptz default now()
);
